import { z } from "zod";
import { validateProjectNumber } from "./project-number";
import { MAX_URLS_PER_TICKET, MAX_URL_LENGTH, validateSubmittedUrl } from "./url-safety";

export const DEPARTMENT_KEYS = [
  "TECHNOLOGY_SUPPORT",
  "TRAINING",
  "ACCOUNTING_SERVICES",
  "MARKETING",
  "LEGAL",
  "IMPROVEMENT_IDEAS",
] as const;

export type DepartmentKeyValue = (typeof DEPARTMENT_KEYS)[number];

/**
 * Narrows an untrusted string -- a URL segment, a query parameter -- to a
 * department key, or null.
 *
 * This exists because Prisma does not treat an out-of-enum value as "no
 * match": querying an enum column with one throws
 * PrismaClientValidationError. `/queue/[departmentKey]` takes its segment
 * straight from the URL, so without this a mistyped or stale link renders the
 * "Something went wrong" boundary instead of the page's own "Department not
 * found or inactive" notice -- a 500 for what is really a 404, in front of
 * whoever followed the link.
 *
 * Deliberately exact rather than forgiving: no case-folding and no trimming.
 * The keys are generated by the app itself (the queue index links, the tour
 * manifest), so anything that does not match exactly came from somewhere that
 * should be corrected, not quietly repaired here.
 */
export function parseDepartmentKey(raw: string): DepartmentKeyValue | null {
  return (DEPARTMENT_KEYS as readonly string[]).includes(raw)
    ? (raw as DepartmentKeyValue)
    : null;
}

export const MIN_DESCRIPTION_LENGTH = 30;
export const MAX_SUBJECT_LENGTH = 150;
export const MAX_DESCRIPTION_LENGTH = 8000;

function normalizeText(value: string): string {
  return value.replace(/\r\n/g, "\n").trim();
}

const urlSchema = z
  .string()
  .max(MAX_URL_LENGTH)
  .refine(
    (v) =>
      validateSubmittedUrl(v, { allowHttp: process.env.NODE_ENV !== "production" }).ok,
    {
      message: "Enter a safe https:// URL (http:// only in local development)",
    },
  );

// Kept as a plain ZodObject (not yet superRefine-wrapped) so callers like
// the client form can still call `.omit()`/`.pick()` on it -- ZodEffects
// (the type superRefine returns) doesn't support those. The cross-field
// project-number check is applied separately in `createTicketSchema` below
// and is re-validated there even if a caller skips it earlier.
export const createTicketObjectSchema = z.object({
  franchiseId: z.string().uuid(),
  subject: z
    .string()
    .trim()
    .min(1, "Subject is required")
    .max(MAX_SUBJECT_LENGTH)
    .transform(normalizeText),
  description: z
    .string()
    .trim()
    .min(
      MIN_DESCRIPTION_LENGTH,
      `Please describe the issue in at least ${MIN_DESCRIPTION_LENGTH} characters`,
    )
    .max(MAX_DESCRIPTION_LENGTH)
    .transform(normalizeText),
  isProjectRelated: z.boolean(),
  projectNumber: z.string().trim().optional(),
  urls: z.array(urlSchema).max(MAX_URLS_PER_TICKET).default([]),
  impact: z.string().trim().max(500).optional(),
  urgencyNote: z.string().trim().max(500).optional(),
  consentAcknowledged: z.literal(true, {
    errorMap: () => ({
      message:
        "You must confirm the ticket does not contain passwords, tokens, payment data, or unneeded personal information",
    }),
  }),
  attemptedArticleIds: z.array(z.string()).default([]),
});

export const createTicketSchema = createTicketObjectSchema.superRefine((data, ctx) => {
  if (data.isProjectRelated) {
    const projectNumber = data.projectNumber ?? "";
    const result = validateProjectNumber(projectNumber);
    if (!result.ok) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["projectNumber"],
        message: result.reason ?? "Invalid project number",
      });
    }
  }
});

export type CreateTicketInput = z.infer<typeof createTicketSchema>;

export const conversationMessageSchema = z.object({
  ticketId: z.string().uuid(),
  body: z
    .string()
    .trim()
    .min(1, "Message cannot be empty")
    .max(5000)
    .transform(normalizeText),
  version: z.number().int().positive(),
});

export const internalNoteSchema = z.object({
  ticketId: z.string().uuid(),
  body: z
    .string()
    .trim()
    .min(1, "Note cannot be empty")
    .max(5000)
    .transform(normalizeText),
});

export const triageActionSchema = z.object({
  ticketId: z.string().uuid(),
  version: z.number().int().positive(),
  franchiseId: z.string().uuid().optional(),
  departmentKey: z.enum(DEPARTMENT_KEYS),
  category: z.string().trim().max(80).optional(),
  priority: z.enum(["LOW", "MEDIUM", "HIGH", "URGENT"]),
  tags: z.array(z.string().trim().min(1).max(40)).max(10).default([]),
  internalNote: z.string().trim().max(2000).optional(),
  assigneeId: z.string().uuid().optional(),
});

export const resolveTicketSchema = z.object({
  ticketId: z.string().uuid(),
  version: z.number().int().positive(),
  resolutionSummary: z.string().trim().min(10).max(4000).transform(normalizeText),
  resolutionSteps: z.string().trim().min(10).max(8000).transform(normalizeText),
});

export const statusChangeSchema = z.object({
  ticketId: z.string().uuid(),
  version: z.number().int().positive(),
  toStatus: z.enum([
    "IN_TRIAGE",
    "WAITING_FOR_CUSTOMER",
    "QUEUED",
    "ASSIGNED",
    "IN_PROGRESS",
    "PENDING",
    "RESOLUTION_REVIEW",
    "RESOLVED",
    "CLOSED",
    "REOPENED",
    "CANCELLED",
  ]),
  reason: z.string().trim().max(2000).optional(),
});
